@startuml
left to right direction
actor Usuario

usecase "Agregar Novela" as UC_Add
usecase "Eliminar Novela" as UC_Delete
usecase "Ver Detalles de Novela" as UC_Details
usecase "Marcar como Favorito" as UC_Favorite
usecase "Sincronizar Datos Manualmente" as UC_SyncManual
usecase "Recibir Notificaciones" as UC_Notifications
usecase "Sincronización Automática" as UC_SyncAuto
usecase "Sincronización Periódica" as UC_SyncPeriodic

Usuario --> UC_Add
Usuario --> UC_Delete
Usuario --> UC_Details
Usuario --> UC_Favorite
Usuario --> UC_SyncManual
Usuario <-- UC_Notifications

UC_SyncAuto <-- (Sistema)
UC_SyncPeriodic <-- (Sistema)
@enduml
